### ISSUE TITLE
rx6900xt driver problem

### ISSUE THREAD

**Issue by 1128247** [ok3721/Gigabyte-B760M-GAMING-DDR4-Hackintosh#1]
Hello, I have encountered some problems when using your EFI. In the Ventura system, rx6900xt is recognized as navi21. Is this normal? And it behaves as if it is not driving the GPU, and the response is very slow.

**Comment by ok3721** [comment]
Hi，6900xt采用Navi 21核心，在Mac中显示Navi21是正常的。
请问你的6900xt具体是什么型号？我看[Unsupported-6900XT-Hackintosh-Fix](https://github.com/TylerLyczak/Unsupported-6900XT-Hackintosh-Fix)这里提到6900xth版（例如瀚铠6900xth）需要修改SSDT和伪造id才能正常工作，可以参考。

**Comment by 1128247** [comment]
多谢，我的那张卡应该就是XTXH版本，我晚上回去试下

**Comment by 1128247** [comment]
可以了，终于可以了！！！
![image](https://github.com/ok3721/Gigabyte-B760M-GAMING-DDR4-Hackintosh/assets/58651426/295b3387-1d08-4392-ae3c-2f42a6e7f304)
